#application config
app:
  name: sward
spring:
  profiles:
    active: demo

#web config
server:
  port: 8080

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5010/sward?stringtype=unspecified
  username: postgres
  password: darth2020

postgresql:
  embbed:
    enable: true
  database: sward
  db:
    port: 5010
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

#soular
soular:
  embbed:
  enable: false
  address: http://soular-ce.demoee.tiklab.net

DATA_HOME: /opt/tiklab/sward

#dfs config
#dfs.service.enabled=false
dfs:
  server:
    enabled: true
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    group: g1
    bucket: sward


#dss config
#dss.service.enabled=false
dss:
  server:
    enabled: true
    port: 6000
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6000
    group: g1
    index: index1

#zip config
unzip:
  path: ${DATA_HOME}/unzip/Jira

#license
licences:
   path: ${DATA_HOME}/licences

base:
  url: http://sward-ce.demoee.tiklab.net

backups:
  time: 0 0 2 * * ?
  dir: /data/sward