
#application config
app:
  name: thoughtware-sward

spring:
  profiles:
    active: release
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml

#web config
server:
  port: 8080


jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.13.1.13:5432/tiklab_kanass?stringtype=unspecified
  username: postgres
  password: darth2020


DATA_HOME: /opt/tiklab/sward

#dfs config
#dfs.server.enabled=false
dfs:
  server:
    enabled: true
    port: 4001
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4001
    group: g1
    bucket: sward

#dcs config
#dcs.server.enabled=false
dcs:
  server:
    enabled: true
    port: 5001
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5001
    group: g1
    database: dcs1
    expire: 7200

#dss config
#dss.server.enabled=false
dss:
  server:
    enabled: true
    port: 6001
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6001
    group: g1
    index: index1

#soular config
soular:
  embbed:
    enable: false
  address: http://e.tiklab.net


#plugin config
plugin:
  path: ${DATA_HOME}/plugin

#zip config
unzip:
  path: ${DATA_HOME}/unzip/Jire

#license
licences:
  path: ${APP_HOME}/licences

homes:
  address: http://172.11.1.11:8080

file:
  path: http://file.dev.thoughtware.io

base:
  url: http://e.sward.tiklab.net
backups:
  time: 0 0 2 * * ?
  dir: /data/sward