#application config
app:
  name: thoughtware-sward

spring:
  profiles:
    active: release
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml


#eas
eas:
  embbed:
    enable: true

#web config
server:
  port: 8080


jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/sward?stringtype=unspecified
  username: postgres
  password: darth2020

postgresql:
  embbed:
    enable: true
  database: sward
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

DATA_HOME: /opt/thoughtware/sward

#dfs config
dfs:
  server:
    enabled: true
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    group: g1
    bucket: sward

#dcs config
#dcs.server.enabled=false
dcs:
  server:
    enabled: true
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    group: g1
    database: dcs1
    expire: 7200
#dss config
#dss.server.enabled=false
dss:
  server:
    enabled: true
    port: 6000
    datapath: ${DATA_HOME}/search
  client:
    url: 127.0.0.1:6000
    group: g1
    index: index1



#plugin config
plugin:
  path: ${DATA_HOME}/plugin

#zip config
unzip:
  path: ${DATA_HOME}/unzip/Jire

#license
licences:
  path: ${APP_HOME}/licences

homes:
  address: http://192.168.10.6:8070

file:
  path: http://file.dev.thoughtware.io


base:
  url: http://e.sward.thoughtware.net

backups:
  time: 0 0 2 * * ?
  dir: /data/sward