#application config
app:
  name: sward

spring:
  profiles:
    active: release
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml

server:
  port: 8080

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:9000/sward?stringtype=unspecified
  username: postgres
  password: darth2020

#soular
soular:
  embbed:
    enable: true
  address: http://soular-ce.test.tiklab.net

#enable mysql
postgresql:
  embbed:
    enable: true
  database: sward
  db:
    port: 9000
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

DATA_HOME: ${user.home}/tiklab/sward

#dfs config
dfs:
  server:
    enabled: true
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    group: g1
    bucket: sward

#dcs config
dcs:
  server:
    enabled: true
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    group: g1
    database: dcs1
    expire: 7200

#dss config
dss:
  server:
    enabled: true
    port: 6000
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6000
    group: g1
    index: index1

#zip config
unzip:
  path: ${DATA_HOME}/unzip/Jira

#license
licences:
  path: ${DATA_HOME}/licences

base:
  url: http://sward-ce.test.tiklab.net

backups:
  time: 0 0 2 * * ?
  dir: /data/sward