#application config
app:
  name: sward
spring:
  profiles:
    active: dev

#web config
server:
  port: 10000

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_sward?stringtype=unspecified
  username: postgres
  password: darth2020

postgresql:
  type: local
  embbed:
    enable: false
  database: tiklab_sward

DATA_HOME: ${user.home}/tiklab/tiklab-sward

#dfs config
dfs:
  server:
    enabled: true
    port: 4001
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4001
    group: g1
    bucket: sward

#dcs config
dcs:
  server:
    enabled: true
    port: 5001
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5001
    group: g1
    database: dcs1
    expire: 7200

#dss config
dss:
  server:
    enabled: true
    port: 6001
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6001
    group: g1
    index: index1

#soular config
soular:
  embbed:
    enable: true
  web:
    address: http://192.168.10.15:8080
  address: http://192.168.10.15:8080



#license
licences:
    path: ${APP_HOME}/licences

#zip config
unzip:
    path: ${DATA_HOME}/unzip/confluence

postin:
  enable: false
  scan:
    package: io.tiklab
  report:
    workspaceId: a79bdd105434
    server: http://e.postin.tiklab.net/

base:
  url: http://192.168.10.7:8060

backups:
  time: 0 0 2 * * ?
  dir: ${DATA_HOME}
  dfs:
    dir: ${DATA_HOME}/files
